THREADS: 32
SAMPLE: [
         "Tanz-1_CENH3_PE150_Rep1_ChIP",
         "Tanz-1_CENH3_PE150_Rep1_input"
        ]
FEATURES:
      chrName: ["Chr1",
                "Chr2",
                "Chr3",
                "Chr4",
                "Chr5"]
MAPPING:
      mode: "both"
      reference: "data/index/Tanz-1.patch.scaffold.Chr"
COVERAGE:
      regionBodyLength: 180
      startLabel: "Start"
      endLabel: "End"
      upstream: 2000
      downstream: 2000
      flankName: "2kb"
      binSize: 10
      binName: "10bp"
      sortRegions: "keep"
