THREADS: 32
SAMPLE: [
         "Ler-0_CENH3_PE150_Rep1_ChIP",
         "Ler-0_CENH3_PE150_Rep1_input"
        ]
FEATURES:
      chrName: [
#                "Chr1_Chr2_Chr3_Chr4_Chr5",
                "Chr1"
#                "Chr2",
#                "Chr3",
#                "Chr4",
#                "Chr5"
               ]
MAPPING:
      mode: "both"
      reference: "data/index/Ler-0_110x.ragtag_scaffolds"
COVERAGE:
      regionBodyLength: 2000
      startLabel: "Start"
      endLabel: "End"
      upstream: 2000
      downstream: 2000
      flankName: "2kb"
      binSize: 10
      binName: "10bp"
      sortRegions: "keep"
